# Generated by Django 4.2.6 on 2023-10-31 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_alter_numero_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numero',
            name='valor',
            field=models.IntegerField(default=0),
        ),
    ]
