# Generated by Django 4.2.6 on 2023-11-23 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_partido'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='arbitro',
            field=models.CharField(choices=[('Sí', 'Sí'), ('No', 'No')], default='Sí', max_length=3),
        ),
        migrations.AddField(
            model_name='partido',
            name='exp',
            field=models.CharField(choices=[('Sí', 'Sí'), ('No', 'No')], default='Sí', max_length=3),
        ),
    ]
