# Generated by Django 4.2.6 on 2023-11-23 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_alter_partido_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='tipo',
            field=models.CharField(choices=[('Dobles', 'Dobles'), ('Individual', 'Individual')], default='Individual', max_length=10),
        ),
    ]
